const fs = require('fs');
const dir = 'knowledge/items/02-tools-actions/BB-2026-05-01-023';
const data = JSON.parse(fs.readFileSync(dir + '/raw/dom-full.json', 'utf8').replace(/^\uFEFF/, ''));
const meta = (k) => (data.metas.find(x => x.property === k || x.name === k) || {}).content;
const title = (meta('og:title') || data.title || 'BB-2026-05-01-023').replace(' | BestBlogs.dev', '');
const desc = meta('og:description') || meta('description') || '';
const author = meta('article:author') || 'Claude Blog';
const time = meta('article:published_time') || '2026-04';
const tags = data.metas.filter(x => x.property === 'article:tag').map(x => x.content);
const content = data.content || '';
fs.writeFileSync(dir + '/article.md', `# ${data.title || title}\n\n- BestBlogs URL: ${data.url}\n- Extraction: DOM text from BestBlogs page\n- Extracted chars: ${content.length}\n\n---\n\n${content}`, 'utf8');
const orig = (data.links || []).find(x => (x.text || '').includes('查看原文'));
const external = (data.links || []).filter(x => x.href && !x.href.includes('bestblogs.dev'));
const sourceLines = ['# Source Evidence','',`- Title: ${data.title || title}`,`- BestBlogs URL: ${data.url}`,`- Original publisher URL: ${orig ? orig.href : 'Not found on page during capture.'}`];
if (orig) sourceLines.push(`- Original link text: ${orig.text}`);
sourceLines.push('', '## Evidence Links Captured', '');
for (const l of external.slice(0,40)) sourceLines.push(`- ${l.text || l.title || l.href}: ${l.href}`);
sourceLines.push('');
fs.writeFileSync(dir + '/source.md', sourceLines.join('\n'), 'utf8');
const summary = `# BB-2026-05-01-023 Summary\n\n## Article\n\n- Title: ${title}\n- Source: BestBlogs / ${author}\n- URL: ${data.url}\n- Date: ${time}\n- Topic: \`02-tools-actions\`\n- Tags: ${tags.join(', ')}\n\n## Model Mapping\n\n- Blocks: Tools/Actions, MCP, Identity/Permissions, Production Systems\n- Layer: tool integration, engineering, guardrails\n\n## Core Takeaway\n\nThis article is relevant because MCP-style integrations connect agents to production systems. The hard part is not only tool calling, but permissions, data access boundaries, observability, and operational safety.\n\n## Reusable Principle\n\nProduction agent tools should be designed as governed interfaces: explicit capability boundaries, clear auth, logs, and recoverable behavior.\n`;
fs.writeFileSync(dir + '/summary.md', summary, 'utf8');
console.log(JSON.stringify({title, desc, author, time, tags, len: content.length, url: data.url, original: orig && orig.href}, null, 2));
